In [1]:
import np
import re
from functools import reduce
import pandas as pd

# Task 1

In [37]:
while True:
    try:
        code_type = input("ELECTRONIC MASTERMIND 1977\nSELECT CODE TYPE: [3, 4, 5]: ").strip()
        if code_type.lower() == "stop":
            print("Terminated", end="\n\n\n")
            break
        N = int(code_type)
        if N not in [3, 4, 5]: raise ValueError()
    except ValueError:
        print("Not a valid code type.", end="\n\n\n")
    else:
        shield = np.random.choice(10, N)
        print(shield, "NOTE: THIS SHOULD BE HIDDEN. IT IS SHOWN FOR DEMO PURPOSES ONLY")
        i = 0
        output = np.array(["."]*N)
        while (output != "B").any():
            try:
                ui = np.array(re.split(r"\s", input("Enter the code separated by space: "))).astype(int)
                if len(ui) != N: raise ValueError("Insufficient Values in Input")
            except ValueError as e:
                print(e if len(str(e)) and not str(e).startswith("invalid literal for int()") else "Unexpected Format for Sequence\n")
            else:
                output = np.array(["."]*N)
                output[np.isin(ui, list(set(shield[ui != shield]) & set(ui[ui != shield])))] = "W"
                output[ui==shield] = "B"
                i += 1
                print("Guess", i, ":", np.sum(output=="B"), np.sum(output=="W"), output,  end="\n\n")

        print("SOLVED:", shield, end="\n\n\n")

ELECTRONIC MASTERMIND 1977
SELECT CODE TYPE: [3, 4, 5]: 3
[6 0 9] NOTE: THIS SHOULD BE HIDDEN. IT IS SHOWN FOR DEMO PURPOSES ONLY
Enter the code separated by space: 1 2 6
Guess 1 : 0 1 ['.' '.' 'W']

Enter the code separated by space: 6 3 0
Guess 2 : 1 1 ['B' '.' 'W']

Enter the code separated by space: 6 0 4
Guess 3 : 2 0 ['B' 'B' '.']

Enter the code separated by space: 6 0 5
Guess 4 : 2 0 ['B' 'B' '.']



KeyboardInterrupt: Interrupted by user

In [ ]:
N = int(input("ELECTRONIC MASTERMIND 1977\nSELECT CODE TYPE: [3, 4, 5]: ").strip())
shield = np.random.choice(10, N)
output = np.array(["."]*N)

dataset = {i:[] for i in range(10)}

while (output != "B").any():
    ui = np.array(re.split(r"\s", input("Enter the code separated by space: "))).astype(int)
    

In [2]:
def mark(shield, guess):
    output = np.full(len(shield), ".", dtype=str)
    output[np.isin(guess, list(set(shield[guess != shield]) & set(guess[guess != shield])))] = "W"
    output[guess==shield] = "B"
    return output


def score(shield, guess):
    return np[(guess==shield).sum(), np.isin(guess, list(set(shield[guess != shield]) & set(guess[guess != shield]))).sum()]

In [3]:
def crossover(code1, code2):
    return np.where(np.random.random(size=len(code1))<0.5, code1, code2)

def mutate(code):
    code[np.random.randint(len(code)-1)] = np.random.randint(9)
    return code

def permute(code):
    for i in range(len(code)):
        if np.random.random() < 0.03: # very low
            a, b = np.random.randint(len(code)-1, size=2)
            code[a], code[b] = code[b], code[a]
    
    return code

def inversion(code):
    code[0], code[-1] = code[-1], code[0]
    return code

In [15]:
crossover([1,2,3],[3,2,1])

array([3, 2, 3])

In [17]:
mutate([1,2,3])

[1, 1, 3]

In [23]:
permute([1,2,3])

[1, 2, 3]

In [30]:
np.random.choice(10, size=(150, 3)).sum(axis=0)

array([720, 679, 630])

In [4]:
def generatePopulation(size=(150,3)):
    pop = np.random.choice(10, size=size)
    df = pd.DataFrame(pop).drop_duplicates()
    while len(df) < size[0]:
        pop = np.random.choice(10, size=(size[0]-len(df), size[-1]))
        df = pd.concat([df, pd.DataFrame(pop)]).drop_duplicates()
    return df.iloc[:size[0]]

In [51]:
code = np[6, 0, 9]
trial = np[1,2,3]
result = score(trial, code)
result

array([0, 0])

In [5]:
def fitness(trial, guesses):
    print(guesses)
    X, Y = np.array([np.abs(score(trial, np.array(guess))-guess_result) for (guess, guess_result) in guesses]).sum(axis=0)
    return X + Y - len(trial)

def stringify(lst):
    return "".join(map(str, lst))

def destringify(lst):
    return list(map(int, list(lst)))

code = np[6, 0, 9]
trial = np[1,2,3]
result = score(trial, code)
turn = 0

print(trial, result, mark(trial, code))

guesses = []
# guesses = [
#     ([1,2,6],[0,1]),
#     ([6,3,0],[1,1]),
#     ([6,0,4],[2,0]),
#     ([6,0,5],[2,0])
    
# ]

while (result != [3,0]).any():
    population = generatePopulation().values

    Ei = []
    h, k = 1, 0

    while len(Ei) <= len(population) and h <= 100:
        #print(population)
        h += 1
        children = np.array(reduce(lambda lst,i:lst+[permute((lambda gene:mutate(gene) if np.random.random()<0.03 else gene)(crossover(population[i],population[i+1])))], range(len(population)-1), [])+[population[-1]])
        pop_score = sorted([(fitness(c, guesses), c) for c in children], key=lambda x:x[0])
        eligibles = [(score, e) for (score, e) in pop_score if score == 0]
        print(eligibles)
        if not len(eligibles): continue
        stringligibles = set([stringify(i[-1]) for i in eligibles])
        Ei_new = set(map(stringify, Ei))
        Ei_new = list(Ei_new - stringligibles)
        Ei_new.extend(list(map(stringify, np.random.choice(10,size=(len(Ei)-len(Ei_new), 3)).tolist())))
        Ei_new = list(set(Ei_new) | stringligibles)[:len(population)]
        Ei = list(map(destringify, Ei_new))
        population = np.vstack((np.array([i[-1] for i in eligibles]),np.random.choice(10,size=(len(Ei)-len(Ei_new), 3))))

    print("Ei", end="")
    if len(Ei) == 0:
        print(" is 0")
        continue
    print(" ", Ei)
    test = Ei.pop()
    while code in [c for (c, r) in guesses]:
        test = Ei.pop()
    
    turn += 1
    
    result = score(test, code)
    print(code, result, mark(test, code))
    guesses.append((code, result))
    
    

[1 2 3] [0 0] ['.' '.' '.']
[]


TypeError: cannot unpack non-iterable numpy.int32 object

In [36]:
code = np[6, 0, 9]
ui = np[5, 0, 0]

def mark(guess, code):
    code += 1
    guess += 1
    output = np.full_like(code, ".", dtype=str)
    output[guess == code] = "B"
    negatize = code * ((code != guess)*2 - 1)
    considerations = []
    print("----------------------------")

    for allele in guess[guess != code]:
        result = "."
        print(allele)
        print(negatize)
        print(considerations)
        if allele in negatize:
            result = "W"
            negatize[np.argmax(negatize == allele)] = -allele
        print(result)
        print("------------------")
        considerations.append(result)

    output[guess != code] = considerations

    return output

marked = np["W", "B", "."]
mark(ui, code)

code [ 7  1 10]
guess [6 1 1]
code != guess [ True False  True]
(code != guess)*2 - 1 [ 1 -1  1]
negatize [ 7 -1 10]
guess[guess != code] [6 1]
----------------------------
6
[ 7 -1 10]
[]
.
------------------
1
[ 7 -1 10]
['.']
.
------------------


array(['.', 'B', '.'], dtype='<U1')

In [41]:
import np
import re
import pandas as pd
from functools import reduce
from itertools import tee, zip_longest


def p(*size): return np.random.random(size=size if len(size) else 1)

def rand(*size): return np.random.randint(10, size=size if len(size) else 1)

def shuffle(arr):
    cp = arr.copy()
    np.random.shuffle(cp)
    return cp

class Chromosome:
    def __init__(self, *args):
        if len(args) == 1: args = args[0]
        self.values = np.array(list(map(int, args))).flatten()
        self.slots = len(self.values)
        
    def copy(self):
        return Chromosome(*self.values.tolist())
    
    def __str__(self):
        return f"Chromosome("+", ".join(map(str, self.values))+")"
    
    def __len__(self):
        return self.slots
    
    def __getitem__(self, i):
        return self.values[i]
    
    def __setitem__(self, i, obj):
        self.values[i] = obj
        
    def randSlots(self, size=1):
        return np.random.randint(self.slots-1, size=size)
        
    def tolist(self):
        return self.values.tolist()

    def stringify(self):
        return "".join(map(str, self.tolist()))
    
    @classmethod
    def destringify(cls, string):
        return cls(*map(int, string))
    
    def crossover(self, other):
        return Chromosome(np.where(p(self.slots)<0.5, self.values, other.values))
    
    def mutate(self):
        code = self.copy()
        if p() < 0.03:
            code[code.randSlots()] = rand()
        return code
    
    def invert(self):
        code = self.copy()
        if p() < 0.03:
            a, b = sorted(tuple(code.randSlots(2)))
            code[a:b] = code[a:b][::-1]
        return code
    
    def scramble(self):
        code = self.copy()
        if p() < 0.03:
            a, b = sorted(tuple(code.randSlots(2)))
            code[a:b] = shuffle(code[a:b])
        return code
    
    def swap(self,a,b):
        self[a], self[b] = self[b], self[a]

    def permute(self):
        code = self.copy()
        for i in range(code.slots):
            if p() < 0.03: # very low
                code.swap(*code.randSlots(2))
        return code
    
    def __hash__(self):
        return int(self.stringify())
    
    def __eq__(self, other):
        return (self.values == other.values).sum()
    
    def __ne__(self, other):
        return self.values != other.values
    
    def within(self, other):
        return np.isin(self.values, other) 
    
    def whites(self, guess):
        return guess.within(list(set(self[guess != self]) & set(guess[guess != self]))).astype(int)
       
    def blacks(self, guess):
        return (self.values == guess.values)
    
    def score(self, guess):
        return np[self == guess, guess.whites(self).sum()]
    
    def mark(self, guess):
        output = np.full_like(self.values, ".", dtype=str)
        output[guess.whites(self)] = "W"
        output[guess.blacks(self)] = "B"
        return output
    
    def markWith(self, optimal):
        guess = self.values.copy()+1
        code = optimal.values.copy()+1
        output = np.full_like(code, ".", dtype=str)
        output[guess == code] = "B"
        negatize = code * ((code != guess)*2 - 1)
        considerations = []

        for allele in guess[guess != code]:
            result = "."
            if allele in negatize:
                result = "W"
                negatize[np.argmax(negatize == allele)] = -allele
            considerations.append(result)

        output[guess != code] = considerations

        return output
    
    def scoreWith(self, optimal):
        output = self.markWith(optimal)
        return np[(output == "B").sum(), (output == "W").sum()]
    
    def fitness(self, guesses):
        return np.array([self.scoreWith(guess)-guess_result for (guess, guess_result) in guesses]).sum() #- self.slots

    
class ChromoSet(list):
    """
    Can be used for guesses, genotype, eligibles etc
    """
    def __init__(self, values=[]):
        self.values = [Chromosome(candidate) for candidate in np.array(values).tolist()]
        super().__init__(self.values)
        
    def __gt__(self, other):
        return len(self) > len(other)
    
    def __ge__(self, other):
        return len(self) >= len(other)
    
    def __lt__(self, other):
        return len(self) < len(other)
    
    def __le__(self, other):
        return len(self) <= len(other)
    
    def filter(self, f):
        return Elite([chromosome for chromosome in self if f(chromosome)])
    
    def tolist(self):
        return list(map(Chromosome.tolist, self))
        

class Elite(ChromoSet):
    def __add__(self, other):
        return Elite(list(set(self) | set(other)))
    def __sub__(self, other):
        return Elite(list(set(self) - set(other)))
    def __str__(self):
        return "["+", ".join(map(str, self))+"]"
    def __repr__(self):
        return "["+", ".join(map(str, self))+"]"
        
        
class Genotype(ChromoSet):
    def __init__(self, size, slots, initial=[]):
        self.size = size
        self.slots = slots
        df = pd.DataFrame(initial)
        while len(df) < size:
            pop = rand(size-len(df), slots)
            df = pd.concat([df, pd.DataFrame(pop)], ignore_index=True).drop_duplicates()
        
        super().__init__(df.iloc[:size].values)
        
    def reproduce(self):
        a, b = tee(self)
        next(b, None)
        return Genotype(len(self), len(self[0]), initial=list(map(lambda chromosomes: chromosomes[0].crossover(chromosomes[1]).mutate().invert().scramble().permute().tolist(), zip_longest(a, b, fillvalue=self[-1]))))
            
def train(guesses):
    pop = Genotype(150, 3)
    Ei = Elite()
    cnt = 0
    while cnt <= 100 and Ei <= pop:
        children = pop.reproduce().filter(lambda child: not child.fitness(guesses))
        if len(children):
            Ei = Ei + children
            pop = Genotype(150, 3, initial=list(map(Chromosome.tolist, Ei)))
        cnt += 1
    
    return Ei


code = Chromosome(rand(3))

init = Chromosome(1,2,3)

print("Code Played:", init)
print(init.scoreWith(code), init.markWith(code))
guesses = [(init, init.scoreWith(code))]

cnt = 1

while cnt <= 100 and guesses[-1][-1][0] != 3:
    Ei = train(guesses)
    if len(Ei) == 0: continue
    possibles = Ei - Elite([i[0].tolist() for i in guesses])
    #print("Elites:",possibles)
    submission = possibles[np.random.randint(len(possibles))]
    print("Code Played:", submission)
    print(submission.scoreWith(code), submission.markWith(code))
    guesses.append((submission, submission.scoreWith(code)))
    cnt += 1
    
print("YOU WIN!")

Code Played: Chromosome(1, 2, 3)
[1 1] ['B' 'W' '.']
Code Played: Chromosome(6, 1, 2)
[1 1] ['.' 'W' 'B']
Code Played: Chromosome(1, 8, 2)
[2 0] ['B' '.' 'B']
Code Played: Chromosome(1, 0, 2)
[2 0] ['B' '.' 'B']
Code Played: Chromosome(1, 2, 7)
[1 2] ['B' 'W' 'W']
Code Played: Chromosome(1, 2, 6)
[1 1] ['B' 'W' '.']
Code Played: Chromosome(2, 1, 3)
[0 2] ['W' 'W' '.']
Code Played: Chromosome(1, 7, 2)
[3 0] ['B' 'B' 'B']
YOU WIN!


In [40]:
print(Chromosome(rand(3)))

Chromosome(3, 7, 6)


In [ ]:
import np
import re
import pandas as pd
from functools import reduce
from itertools import tee, zip_longest


def p(*size): return np.random.random(size=size if len(size) else 1)

def rand(*size): return np.random.randint(10, size=size if len(size) else 1)

def shuffle(arr):
    cp = arr.copy()
    np.random.shuffle(cp)
    return cp

class Chromosome:
    def __init__(self, *args):
        if len(args) == 1: args = args[0]
        self.values = np.array(list(map(int, args))).flatten()
        self.slots = len(self.values)
        
    def copy(self):
        return Chromosome(*self.values.tolist())
    
    def __str__(self):
        return f"Chromosome("+", ".join(map(str, self.values))+")"
    
    def __len__(self):
        return self.slots
    
    def __getitem__(self, i):
        return self.values[i]
    
    def __setitem__(self, i, obj):
        self.values[i] = obj
        
    def randSlots(self, size=1):
        return np.random.randint(self.slots-1, size=size)
        
    def tolist(self):
        return self.values.tolist()

    def stringify(self):
        return "".join(map(str, self.tolist()))
    
    @classmethod
    def destringify(cls, string):
        return cls(*map(int, string))
    
    def crossover(self, other):
        return Chromosome(np.where(p(self.slots)<0.5, self.values, other.values))
    
    def mutate(self):
        code = self.copy()
        if p() < 0.03:
            code[code.randSlots()] = rand()
        return code
    
    def invert(self):
        code = self.copy()
        if p() < 0.03:
            a, b = sorted(tuple(code.randSlots(2)))
            code[a:b] = code[a:b][::-1]
        return code
    
    def scramble(self):
        code = self.copy()
        if p() < 0.03:
            a, b = sorted(tuple(code.randSlots(2)))
            code[a:b] = shuffle(code[a:b])
        return code
    
    def swap(self,a,b):
        self[a], self[b] = self[b], self[a]

    def permute(self):
        code = self.copy()
        for i in range(code.slots):
            if p() < 0.03: # very low
                code.swap(*code.randSlots(2))
        return code
    
    def __hash__(self):
        return int(self.stringify())
    
    def __eq__(self, other):
        return (self.values == other.values).sum()
    
    def __ne__(self, other):
        return self.values != other.values
    
    def within(self, other):
        return np.isin(self.values, other) 
    
    def whites(self, guess):
        return guess.within(list(set(self[guess != self]) & set(guess[guess != self]))).astype(int)
       
    def blacks(self, guess):
        return (self.values == guess.values)
    
    def score(self, guess):
        return np[self == guess, guess.whites(self).sum()]
    
    def mark(self, guess):
        output = np.full_like(self.values, ".", dtype=str)
        output[guess.whites(self)] = "W"
        output[guess.blacks(self)] = "B"
        return output
    
    def markWith(self, optimal):
        guess = self.values.copy()+1
        code = optimal.values.copy()+1
        output = np.full_like(code, ".", dtype=str)
        output[guess == code] = "B"
        negatize = code * ((code != guess)*2 - 1)
        considerations = []

        for allele in guess[guess != code]:
            result = "."
            if allele in negatize:
                result = "W"
                negatize[np.argmax(negatize == allele)] = -allele
            considerations.append(result)

        output[guess != code] = considerations

        return output
    
    def scoreWith(self, optimal):
        output = self.markWith(optimal)
        return np[(output == "B").sum(), (output == "W").sum()]
    
    def fitness(self, guesses):
        return np.abs(np.array([self.scoreWith(guess)-guess_result for (guess, guess_result) in guesses])).sum() #- self.slots

    
class ChromoSet(list):
    """
    Can be used for guesses, genotype, eligibles etc
    """
    def __init__(self, values=[]):
        self.values = [Chromosome(candidate) for candidate in np.array(values).tolist()]
        super().__init__(self.values)
        
    def __gt__(self, other):
        return len(self) > len(other)
    
    def __ge__(self, other):
        return len(self) >= len(other)
    
    def __lt__(self, other):
        return len(self) < len(other)
    
    def __le__(self, other):
        return len(self) <= len(other)
    
    def filter(self, f):
        return Elite([chromosome for chromosome in self if f(chromosome)])
    
    def tolist(self):
        return list(map(Chromosome.tolist, self))
        

class Elite(ChromoSet):
    def __add__(self, other):
        return Elite(list(set(self) | set(other)))
    def __sub__(self, other):
        return Elite(list(set(self) - set(other)))
    def __str__(self):
        return "["+", ".join(map(str, self))+"]"
    def __repr__(self):
        return "["+", ".join(map(str, self))+"]"
        
        
class Genotype(ChromoSet):
    def __init__(self, size, slots, initial=[]):
        self.size = size
        self.slots = slots
        df = pd.DataFrame(initial)
        while len(df) < size:
            pop = rand(size-len(df), slots)
            df = pd.concat([df, pd.DataFrame(pop)], ignore_index=True).drop_duplicates()
        
        super().__init__(df.iloc[:size].values)
        
    def reproduce(self):
        a, b = tee(self)
        next(b, None)
        return Genotype(len(self), len(self[0]), initial=list(map(lambda chromosomes: chromosomes[0].crossover(chromosomes[1]).mutate().invert().scramble().permute().tolist(), zip_longest(a, b, fillvalue=self[-1]))))


code_type = input("ELECTRONIC MASTERMIND 1977\nSELECT CODE TYPE: [3, 4, 5]: ").strip()
N = int(code_type)

def train(guesses):
    pop = Genotype(150, N)
    Ei = Elite()
    cnt = 0
    while cnt <= 100 and Ei <= pop:
        children = pop.reproduce().filter(lambda child: not child.fitness(guesses))
        if len(children):
            Ei = Ei + children
            pop = Genotype(150, N, initial=list(map(Chromosome.tolist, Ei)))
        cnt += 1
    
    return Ei

code = Chromosome(rand(N))
init = Chromosome(rand(N))

print("Guess 0:", *init)
print(init.scoreWith(code), init.markWith(code))
guesses = [(init, init.scoreWith(code))]

cnt = 1

while cnt <= 100 and guesses[-1][-1][0] != N:
    Ei = train(guesses)
    if len(Ei) == 0: continue
    possibles = Ei - Elite([i[0].tolist() for i in guesses])
    #print("Elites:",possibles)
    submission = possibles[np.random.randint(len(possibles))]
    print(f"Guess {cnt}:", *submission)
    print(submission.scoreWith(code), submission.markWith(code))
    guesses.append((submission, submission.scoreWith(code)))
    cnt += 1
    
print("YOU WIN!")

ELECTRONIC MASTERMIND 1977
SELECT CODE TYPE: [3, 4, 5]: 5
Guess 0: 1 6 0 1 3
[1 1] ['W' 'B' '.' '.' '.']
Guess 1: 6 8 8 1 6
[1 2] ['B' '.' '.' 'W' 'W']
Guess 2: 1 3 8 4 8
[0 1] ['W' '.' '.' '.' '.']
Guess 3: 6 6 6 2 1
[3 0] ['B' 'B' '.' '.' 'B']
Guess 4: 6 6 7 9 1
[3 1] ['B' 'B' 'W' '.' 'B']


In [ ]:
sorted(guesses, key=lambda arr: -arr[1][0])